lsi: false
safe: true
source: "https://franpola.github.io"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: Kramdown
github_button_location_top_navbar: true