lsi: false
safe: true
source: "https://franpola.github.io"
incremental: false
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
gist:
  noscript: false
github_button_location_top_navbar: true