lsi: false
safe: true
source: "https://franpola.github.io"
incremental: false
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 syntax_highlighter: rouge


theme: jekyll-theme-architect